### ISSUE TITLE
Error / missing file in DeepSentiment

### ISSUE THREAD

**Issue by robtow** [vyassu/DeepSentiment#1]
Hi,

I cloned the repo, and installed a number of packages beside those listed in the README. 

I am unable to get it to run successfully.

After running <./script.sh>...

(1) If I do the standalone / command line invocation on a WAV file I get a missing file error:
`IOError: File /home/rob/Desktop/DeepSentiment/DeepSentiment/Test-TrainingData_SVM.csv does not exist`

(2) If I try the web interface, again with a stored file to upload, I get an error message saying that the backend server is not responding; please try again after sometime.

There appears to be some missing resources.

I would like to try to get this running; it looks quite interesting!

-Rob-

**Comment by vyassu** [comment]
Hey Rob,

I have uploaded the missing files and ironed out some of the issues within the Python and script files. Please download the latest code from the repository.

Regards
Vyas

**Comment by vyassu** [comment]
Issue fixed
