### ISSUE TITLE
Hello vyassu , Can you give me some hints about how to bulid my own model on Spark? Thank you!

### ISSUE THREAD

**Issue by zhangxing753951** [vyassu/DeepSentiment#13]

**Comment by vyassu** [comment]
First you have to train the voice data using https://github.com/vyassu/DeepSentiment/blob/master/Code/Spark/SpeechNetSVMMulticlass.py#L140
Second train your speech data using method https://github.com/vyassu/DeepSentiment/blob/master/Code/Spark/SVMSentimentAnalysis_Spark.py#L79

Unfortunately I cannot provide you with any .wav file
