### ISSUE TITLE
Need proper input .wav files

### ISSUE THREAD

**Issue by mskarthi96** [vyassu/DeepSentiment#14]
can someone send me a proper wav files which will work in this model to get accurate results and how can i use sparks to train my own datasets please help............

**Comment by vyassu** [comment]
First you have to train the voice data using https://github.com/vyassu/DeepSentiment/blob/master/Code/Spark/SpeechNetSVMMulticlass.py#L140
Second train your speech data using method https://github.com/vyassu/DeepSentiment/blob/master/Code/Spark/SVMSentimentAnalysis_Spark.py#L79

Unfortunately I cannot provide you with any .wav file
